### ISSUE TITLE
TroPi on RockPro64

### ISSUE THREAD

**Issue by clariion** [Angoosh/RockPro64-RP64.GPIO#2]
Hi Angoosh,,

I would like to use TroPi LEDs on my RockPro64 (for ambient light).
(https://www.piborg.org/blog/build/tropi-getting-started)
Currently it is supported just by Raspberries. 
Is there a way to fix GPIO and to get it to work?

Error I get:

rock64@rockpro64:~/Rock64-R64.GPIO/tropi$ python fuzz.py
Error: Unable to export GPIO
Error: Unable to set GPIO direction
Error: Unable to export GPIO
Error: Unable to set GPIO direction
You must setup() the GPIO channel (BCM 23) as an output first
You must setup() the GPIO channel (BCM 24) as an output first
Running fuzz demo. Press CTRL+C to finish
You must setup() the GPIO channel (BCM 23) as an output first
You must setup() the GPIO channel (BCM 24) as an output first
You must setup() the GPIO channel (BCM 23) as an output first
You must setup() the GPIO channel (BCM 23) as an output first
You must setup() the GPIO channel (BCM 24) as an output first

I would donate for lot of beer!

**Comment by Angoosh** [comment]
Are you using any library for the HAT? also send me the code of fuzz.py please. I'll do my best to make it compatible.

**Comment by clariion** [comment]
I have attached here the TroPi.zip. 
In the main file Tropi.py, I have changed the line "import RPi.GPIO as GPIO" to "import R64.GPIO as GPIO".
(There are other files like "fuzz.py, cheerlights.py, colourwave.py, whichlight.py" they are just for different LED lightining)
When I run: python fuzz.py, the error is occuring. (the same error occurs, no matter which file I use.)

[TroPi-master.zip]
(https://github.com/Angoosh/RockPro64-RP64.GPIO/files/5134739/TroPi-master.zip)

**Comment by Angoosh** [comment]
Thanks, I'll look into it in the evening. (Czech Republic)

**Comment by Angoosh** [comment]
Did you try to run any of the apps under sudo?

**Comment by clariion** [comment]
hmm probably yes, but not sure. I will test it.
I will be arround 17:30 @home and will give an update.

**Comment by clariion** [comment]
It works :-D
Thanks man. Give me your PayPal link!

**Comment by Angoosh** [comment]
sure thing and no worries :D https://www.paypal.me/angoosh

**Comment by clariion** [comment]
It's running without any issues on:
Linux rockpro64 5.6.0-1137-ayufan-ge57f05e7bf8f #ayufan SMP Wed Apr 15 10:16:02 UTC 2020 aarch64 GNU/Linux
and
Linux rockpro64 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310 #1 SMP Wed Aug 28 08:59:34 UTC 2019 aarch64 GNU/Linux!
